# Generated by Django 3.2.5 on 2021-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JavaScriptPunctuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('correctAnswer', models.CharField(max_length=200)),
                ('distractor1', models.CharField(max_length=200)),
                ('distractor2', models.CharField(blank=True, max_length=200)),
                ('distractor3', models.CharField(blank=True, max_length=200)),
                ('distractor4', models.CharField(blank=True, max_length=200)),
                ('questionImage', models.ImageField(blank=True, upload_to='')),
                ('isTrueFalse', models.BooleanField(default=False)),
                ('timesShown', models.IntegerField()),
                ('timesAnswered', models.IntegerField()),
                ('timesAnsweredCorrectly', models.IntegerField()),
                ('timesDistractor1', models.IntegerField()),
                ('timesDistractor2', models.IntegerField()),
                ('timesDistractor3', models.IntegerField()),
                ('timesDistractor4', models.IntegerField()),
            ],
        ),
    ]
