# Generated by Django 3.2.5 on 2021-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_app', '0002_auto_20210716_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='distractor2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='distractor3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='distractor4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='timesAnswered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='timesAnsweredCorrectly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='timesDistractor1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='timesDistractor2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='timesDistractor3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='timesDistractor4',
            field=models.IntegerField(default=0),
        ),
    ]
