# Generated by Django 3.2.5 on 2021-07-28 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mc_app', '0003_auto_20210716_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='javascriptpunctuation',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
