# Generated by Django 3.2.5 on 2021-07-28 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mc_app', '0004_javascriptpunctuation_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='derivativesSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=200, unique=True)),
                ('skillDescription', models.CharField(max_length=400)),
                ('numberNeededForMastery', models.IntegerField(default=7)),
                ('consecutiveNeededForMastery', models.IntegerField(default=4)),
                ('timesAttempted', models.IntegerField(default=0)),
                ('timesMastered', models.IntegerField(default=0)),
                ('totalQuestionsAsked', models.IntegerField(default=0)),
                ('totalQuestionsAnsweredCorrectly', models.IntegerField(default=0)),
                ('longestStreak', models.IntegerField(default=0)),
                ('percentCorrect', models.IntegerField(default=100)),
            ],
        ),
        migrations.AlterField(
            model_name='javascriptpunctuation',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='userSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionCount', models.IntegerField(default=0)),
                ('sessionStartTime', models.DateTimeField(auto_now_add=True)),
                ('sessionEndTime', models.DateTimeField()),
                ('skillsCompletedCount', models.IntegerField(default=0)),
                ('quizzesCompletedCount', models.IntegerField(default=0)),
                ('sessionUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSkillsMastered', models.IntegerField(default=0)),
                ('totalQuizzesMastered', models.IntegerField(default=0)),
                ('totalQuestionsAttempted', models.IntegerField(default=0)),
                ('totalQuestionsAnsweredCorrectly', models.IntegerField(default=0)),
                ('longestStreak', models.IntegerField(default=0)),
                ('percentCorrect', models.IntegerField(default=100)),
                ('masteredBasicDerivatives', models.BooleanField(default=False)),
                ('basicDerivativesMaxCorrect', models.IntegerField(default=0)),
                ('basicDerivativesPercentCorrect', models.IntegerField(default=100)),
                ('masteredNegativeCoefficients', models.BooleanField(default=False)),
                ('negativeCoefficientsMaxCorrect', models.IntegerField(default=0)),
                ('negativeCoefficientsPercentCorrect', models.IntegerField(default=100)),
                ('masteredFractionalCoefficients', models.BooleanField(default=False)),
                ('fractionalCoefficientsMaxCorrect', models.IntegerField(default=0)),
                ('fractionalCoefficientsPercentCorrect', models.IntegerField(default=100)),
                ('masteredBasicMix', models.BooleanField(default=False)),
                ('basicMixMaxCorrect', models.IntegerField(default=0)),
                ('basicMixPercentCorrect', models.IntegerField(default=100)),
                ('masteredNegativeExponents', models.BooleanField(default=False)),
                ('negativeExponentsMaxCorrect', models.IntegerField(default=0)),
                ('negativeExponentsPercentCorrect', models.IntegerField(default=100)),
                ('masteredFractionalExponents', models.BooleanField(default=False)),
                ('fractionalExponentsMaxCorrect', models.IntegerField(default=0)),
                ('fractionalExponentsPercentCorrect', models.IntegerField(default=100)),
                ('masteredAdvancedMix', models.BooleanField(default=False)),
                ('advancedMixMaxCorrect', models.IntegerField(default=0)),
                ('advancedMixPercentCorrect', models.IntegerField(default=100)),
                ('progressForUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
